name: Deploy to Vercel

on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: team_dmTODz1eqA2otYqtrwXsr1Xi
  VERCEL_PROJECT_ID: prj_L1CWZPqUygqaDZpeEJkANdp0KwcN

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      - name: Deploy to production
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
